apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: mgsantos89/gitopsfc
  newTag: 0d3f35a9097c4eaf6e83fe4ed999e7f2c48f22e1
